version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.0
    hostname: loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    hostname: promtail
    build: ./promtail

  grafana:
    image: grafana/grafana:9.0.0
    hostname: grafana
    environment:
      - GF_PATHS_PROVISIONING
      - GF_AUTH_ANONYMOUS_ENABLED
      - GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - ./grafana/provisioning/datasources/ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    ports:
      - "127.0.0.1:${LOCAL_GF_PORT:-3000}:3000"
